#!/bin/bash

alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias cd..="cd .."

alias 1='cd -'
alias 2='cd -2'
alias 3='cd -3'
alias 4='cd -4'
alias 5='cd -5'
alias 6='cd -6'
alias 7='cd -7'
alias 8='cd -8'
alias 9='cd -9'
alias _='sudo '
alias afind='ack -il'


# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias cp="cp -iv"
#             │└─ list copied files
#             └─ prompt before overwriting an existing file

alias mkdir="mkdir -pv"
#                   │└─ list created directories
#                   └─ create intermediate directories

alias mv="mv -iv"
#             │└─ list moved files
#             └─ prompt before overwriting an existing file

alias rm="rm -rf --"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

alias :q="exit"
alias c="clear"
alias ch="history -c && > ~/.bash_history"
alias e="vim --"
alias ip="dig +short myip.opendns.com @resolver1.opendns.com"
alias m="man"
alias map="xargs -n1"
alias n="npm"
alias p="cd ~/projects"
alias path='printf "%b\n" "${PATH//:/\\n}"'
alias q="exit"
alias t="tmux"
alias y="yarn"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# LS
alias l='ls -lah'
alias la='ls -lAh'
alias ll='ls -lh'
alias ls='ls -G'
alias lsa='ls -lah'
alias md='mkdir -p'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# MAVEN
alias mvn=mvn-or-mvnw
alias 'mvn!'='mvn -f $(git rev-parse --show-toplevel 2>/dev/null || echo ".")/pom.xml'
alias mvn-updates='mvn versions:display-dependency-updates'
alias mvnag='mvn archetype:generate'
alias mvnboot='mvn spring-boot:run'
alias mvnc='mvn clean'
alias mvncd='mvn clean deploy'
alias mvnce='mvn clean eclipse:clean eclipse:eclipse'
alias mvnci='mvn clean install'
alias mvncie='mvn clean install eclipse:eclipse'
alias mvncini='mvn clean initialize'
alias mvncist='mvn clean install -DskipTests'
alias mvncisto='mvn clean install -DskipTests --offline'
alias mvncom='mvn compile'
alias mvncp='mvn clean package'
alias mvnct='mvn clean test'
alias mvncv='mvn clean verify'
alias mvncvst='mvn clean verify -DskipTests'
alias mvnd='mvn deploy'
alias mvndocs='mvn dependency:resolve -Dclassifier=javadoc'
alias mvndt='mvn dependency:tree'
alias mvne='mvn eclipse:eclipse'
alias mvnjetty='mvn jetty:run'
alias mvnp='mvn package'
alias mvns='mvn site'
alias mvnsrc='mvn dependency:sources'
alias mvnt='mvn test'
alias mvntc='mvn tomcat:run'
alias mvntc7='mvn tomcat7:run'
# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# GIT
alias g="git"

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# yarn
alias y=yarn
alias ya='yarn add'
alias yad='yarn add --dev'
alias yap='yarn add --peer'
alias yb='yarn build'
alias ycc='yarn cache clean'
alias yd='yarn dev'
alias yga='yarn global add'
alias ygls='yarn global list'
alias ygrm='yarn global remove'
alias ygu='yarn global upgrade'
alias yh='yarn help'
alias yi='yarn init'
alias yin='yarn install'
alias yln='yarn lint'
alias yls='yarn list'
alias yout='yarn outdated'
alias yp='yarn pack'
alias yrm='yarn remove'
alias yrun='yarn run'
alias ys='yarn serve'
alias yst='yarn start'
alias yt='yarn test'
alias ytc='yarn test --coverage'
alias yuc='yarn global upgrade && yarn cache clean'
alias yui='yarn upgrade-interactive'
alias yup='yarn upgrade'
alias yv='yarn version'
alias yw='yarn workspace'
alias yws='yarn workspaces'

# - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
# Load OS specific configs.

. "$OS/bash_aliases"
